name: weather_mobile_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  internet_connection_checker: ^0.0.1+1

  flutter_bloc: ^7.0.1

  http: ^0.13.3

  get_it: ^7.2.0

  provider: ^5.0.0

  carousel_slider: ^4.0.0

  cached_network_image: ^3.1.0

  auto_size_text: ^3.0.0-nullsafety.0

  intl: ^0.17.0

  font_awesome_flutter: ^9.1.0

  google_place: ^0.4.3

  geolocator: ^7.6.0

  flutter_geocoder: ^0.2.2-nullsafety

  dartz: ^0.10.0-nullsafety.2


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/images/background.jpeg
    - assets/images/powered_by_google.png
